# Plugins
gems:
- jekyll-sitemap
safe: false


# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "4th Strategic Meeting for Medaka Research & 3th Regional Fish Meeting"
email: "lazaro.centanin@cos.uni-heidelberg.de"
description: "4th Strategic Meeting for Medaka Research & 3th Regional Fish Meeting"
baseurl: "/zeppelin"
url: "https://gdg-x.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Centre for Organismal Studies Heidelberg"
organizerAlternateName: "Centre for Organismal Studies Heidelberg"
organizerDescription: "The Centre for Organismal Studies (COS) Heidelberg aims to study organismic biology beyond the borders of organisational level."
organizerEmail: "lazaro.centanin@cos.uni-heidelberg.de"
organizerLogo: "/img/seo/coslogo204.png"
organizerLink: "https://www.cos.uni-heidelberg.de/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/coslogo204.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Programm"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/logistics/", text: "Logistics"}
bottomNavigationLinks:
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSf7N_jo1rg3WZdbJY0y6X2Ipgsaacl22q7KJC4NtLJqFsns3Q/viewform?usp=sf_link", text: "Registration"}
rightNavigationButtons:
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSf7N_jo1rg3WZdbJY0y6X2Ipgsaacl22q7KJC4NtLJqFsns3Q/viewform?usp=sf_link", text: "Registration"}

# Hero Block
heroImage: "SagitalGIF-ProperScale.gif"
heroTitle: "4th Strategic Meeting for Medaka Research <br> 3th Regional Fish Meeting"
eventDate: "16-18 April 2018 <br> Deadline for Registration and Abstract submission: February 28th"
heroButtons:
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSf7N_jo1rg3WZdbJY0y6X2Ipgsaacl22q7KJC4NtLJqFsns3Q/viewform?usp=sf_link", text: "Registration"}
hotelButton: "Hotel Information"

# Rockstar Speakers Block
rockstarSpeakersImage: "alte_uni_saal_small.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Confirmed Speakers"
rockstarSpeakersButtonText: "See all speakers"

#Sponsor Block
sponsorsTitle: "Sponsors"

# Venue1 Block
venue1BlockTitle: "Venue Day 1"
venue1BigImage: ""
venue1SmallImage1: "alte_uni.jpg"
venue1SmallImage2: "alte_uni_saal_medium.jpg"
venue1SmallImage3: ""
venue1Title: "Alte Aula - Old Assembly Hall"
venue1Features: ["Venue 16th April 2018", "Registration Opening 10:00am", "Located directly in the city center"]

# Venue2 Block
venue2BlockTitle: "Venue Day 2-3"
venue2BigImage: ""
venue2SmallImage1: "Leben_Logo_bunt.jpg"
venue2SmallImage2: "COSAuditorium.jpg"
venue2SmallImage3: ""
venue2Title: "COS - Im Neuenheimer Feld 230"
venue2Features: ["Venue 17th-18th April 2018", "Bertalanffy Lecture Hall and Seminar room 005", "Located in Neuenheimer Feld campus"]

# Organization Block
rockstarSpeakersImage: "alte_uni_saal_small.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Confirmed Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Partners Block
organizersTitle: "Organizers"
sponsorsTitle: "Sponsors"
partnersTitle: "Hotels"
hotelButton: "Hotel Information"


# Footer
socialLinks: null
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.cos.uni-heidelberg.de/?l=_e", text: "COS Heidelberg"}
   - {link: "http://www.uni-heidelberg.de/index_e.html", text: "Heidelberg University"}
   - {link: "http://www.heidelberg.de/hd,Len/300652.html", text: "Information about Heidelberg"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:lazaro.centanin@cos.uni-heidelberg.de", text: "lazaro.centanin@cos.uni-heidelberg.de"}
   - {link: "https://goo.gl/maps/xMkr4hkHoNA2", text: "COS <br> Im Neuenheimer Feld 230 <br> 69120 Heidelberg"}
 -
  title: "Sitemap"
  links:
   - {permalink: "/", text: "Home"}
   - {permalink: "/schedule/", text: "Programm"}
   - {permalink: "/speakers/", text: "Speakers"}
   - {permalink: "/logistics/", text: "Logistics"}
 -
  title: "Account Info for Registration Fee"
  links:
   - {text: "Account holder: Universität Heidelberg<br>
Bank: BW-Bank Stuttgart<br>
IBAN: DE69 6005 0101 7421 5004 36<br>
SWIFT/BIC: SOLADEST600<br>
Address: Kleiner Schlossplatz 11, 70173 Stuttgart<br> 
Reference I (urgently needed): 2300091 Medaka Meeting<br>
Reference II: your name"}

# Speakers List Block
showSessions: true

# Logistics Map New Block
locationmapnewBlockTitle: "In Heidelberg"
locationmapnewBigImage: ""
locationmapnewSmallImage1: "alte_uni.jpg"
locationmapnewSmallImage2: "alte_uni_saal_medium.jpg"
locationmapnewSmallImage3: "marstall.jpg"

# Logistics Direction Details Block
directionDetailsImage: "10-Hedelberg.JPG"
directionDetailsTitle: "Get around Heidelberg"
directionDetailsCards:
 - {title: "From the Frankfurt Airport", information: 'Heidelberg is about an hour away from Frankfurt Int. Airport. It is easily reachable by <a href="https://www.bahn.com/en/view/index.shtml">train</a> or shuttle busses.<br>More information about shuttle busses:<br><a href="http://frankfurt-airport-shuttles.de/en/home-2/">- Non-stop airport shuttle service</a><br><a href="https://www.tls-heidelberg.de/en/">- Door to Door airport shuttle service</a><br><a href="https://www.flixbus.com/">- Low cost intercity bus</a>'}
 - {title: "Public Transit", information: 'Trams and busses are available in Heidelberg and provide comfortable access to all venues. 
Get more information about <br>
<a href="https://www.vrn.de/mng/#/XSLT_TRIP_REQUEST2@init">- Time schedule</a><br>
<a href="https://www.rnv-online.de/fileadmin/user_upload/downloads/Plaene/Liniennetzplaene/Liniennetzplan_HD.pdf">- Map of public transport lines</a><br>
<a href="https://www.vrn.de/tickets/ticketuebersicht/index.html">- Tickets (only in german available)</a><br>
The following tickets are the important ones:<br>
<a href="https://www.vrn.de/tickets/ticketuebersicht/tages-karten/tages-karte/index.html#info">- One day ticket (6,50€ (+2,70€ per additional person))</a><br>
<a href="https://www.vrn.de/tickets/ticketuebersicht/city-tarif/heidelberg/index.html#info">- City tarif (1,30€)</a> between Main station and historic center<br>
<a href="https://www.vrn.de/tickets/ticketuebersicht/einzelfahrschein/erwachsene/index.html#info">- Normal tarif (2,50€)</a> provide access to Campus Neuenheimer Feld<br>
<a href="https://www.vrn.de/tickets/ticketuebersicht/mehrfahrtenkarte/erwachsene/index.html#info"> (5 tickets for 11,90€ (2,38€))</a><br>
You can buy the tickets online, at ticket machines, from the bus drivers (not in trams) or in ticket shops of DB or RNV/VRN.'}
 - {title: "Via Public Transit to the Venues", information: 'There are some useful train and bus stops which are good to know. Please check <a href="https://www.rnv-online.de/fileadmin/user_upload/downloads/Plaene/Liniennetzplaene/Liniennetzplan_HD.pdf">this map</a> for more details.<br>
Stops at the venues:<br>
<a href="https://www.vrn.de/mng/#/XSLT_TRIP_REQUEST2@init?restriction=0&dest=Heidelberg,%20Universit%C3%A4tsplatz&isDeparture=true">- Universitätsplatz</a> is directly in front of the venue of day 1 and is located in the heart of the historic center. Available Busses: 31/32<br>
<a href="https://www.vrn.de/mng/#/XSLT_TRIP_REQUEST2@init?restriction=0&dest=Heidelberg,%20Bunsengymnasium&isDeparture=true">- Bunsengymnasium</a> is the nearest stop to the venue of day 2/3 and just a 2min walk away. The venue is directly behind the new Mathematikon-building. Available busses: 31, available trams: 21/24.<br>'}

# Logistics Hotel Info Block
hotel-infoImage: "06-Hedelberg.JPG"
hotel-infoTitle: "Information about Partner Hotels"
hotel-infoCards:
 - {title: "NH Hotel Heidelberg", information: 'The <a href="https://www.nh-hotels.de/hotel/nh-heidelberg">NH Hotel</a> is the "first choice" partner hotel and will be the speakers hotel.<br>It is located in the <a href="https://goo.gl/maps/rEXQF8fCpr52">Bergheimer Str. 91</a>.<br>
Contingent name: COS Medaka<br>
Booking number: MB0000964229<br>
20 Standard Double rooms for single use including breakfast (for double use if needed – plus 19,90.- per night)<br>
!!! NB: price for first night is lower than for the other two nights:<br>
15.04.18: 121,05.-<br>
16.04.18: 155,05.-<br>
17.04.18: 155,05.-<br>
For your reservation, please send an email to <a href="mailto:nhheidelberg@nh-hotels.com?subject=Reservation Contingent COS Medaka&body=Contingent name COS Medaka%0D%0ABooking number MB0000964229">nhheidelberg@nh-hotels.com</a>.'}

 - {title: "The Heidelberg Exzellenz Hotel", information: 'The <a href="www.exzellenzhotel.de">Exzellenz Hotel</a> is located in the <a href="https://goo.gl/maps/3aC459FKWdM2">Rohrbacher Straße 29</a>.<br>
Contingent name: COS Medaka<br>
20 Rooms, reservation from April 15 (arrival) to 18 (departure)<br>
10 EZ/Single Rooms: 89.- EUR<br>
10 DZ/Double Rooms: 115.- EUR<br>
all Doubles also usable as Single Rooms : 95.- EUR<br>
All prices including breakfast<br>
For your reservation, please send an email to <a href="mailto:info@exzellenzhotel.de?subject=Reservation Contingent COS Medaka">info@exzellenzhotel.de</a>.'}

 - {title: "Hotel Classic Inn", information: 'The <a href=" http://www.hotel-classic-inn.de">Hotel Classic Inn</a> is located in the <a href="https://goo.gl/maps/cYXKr2F9URU2">Belfortstraße 3</a>.<br>
Contingent name: COS Medaka<br>
12 rooms reserved<br>
6 EZ/Single Rooms:  72.-€<br>
6 DZ/Double Rooms:  89.-€<br>
All rooms excl. breakfast, breakfast at 6.- EUR/day<br>
For your reservation, please send an email to <a href="mailto:info@hotel-classic-inn.de?subject=Reservation Contingent COS Medaka">info@hotel-classic-inn.de</a>.'}
